import { Product, FAQItem, Order, User } from "@/types"

export const mockProducts: Product[] = [
  {
    id: "rec1",
    name: "Ethereal Gold Chain Necklace",
    slug: "ethereal-gold-chain-necklace",
    description: "A delicate 22K gold chain necklace that catches the light with every movement. Handcrafted by master artisans, this piece embodies the quiet luxury of minimal design. Perfect for layering or wearing alone as a statement of understated elegance.",
    price: 28500,
    originalPrice: 32000,
    images: [
      "/images/product-1.jpg",
    ],
    category: "Necklaces",
    subcategory: "Chains",
    tags: ["gold", "minimal", "layering", "daily-wear"],
    inStock: true,
    stockCount: 12,
    material: "22K Gold",
    weight: "4.2g",
    dimensions: "Length: 18 inches",
    featured: true,
    newArrival: false,
    bestseller: true,
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "rec2",
    name: "Luna Pearl Drop Earrings",
    slug: "luna-pearl-drop-earrings",
    description: "Freshwater pearls suspended from 18K gold hooks, creating a luminous drop that frames the face beautifully. Each pearl is hand-selected for its lustre and shape, making every pair subtly unique.",
    price: 18500,
    images: [
      "/images/product-2.jpg",
    ],
    category: "Earrings",
    subcategory: "Drops",
    tags: ["pearl", "gold", "elegant", "evening"],
    inStock: true,
    stockCount: 8,
    material: "18K Gold, Freshwater Pearl",
    weight: "3.1g",
    dimensions: "Drop: 2.5cm",
    featured: true,
    newArrival: true,
    bestseller: false,
    createdAt: "2024-02-20T10:00:00Z",
  },
  {
    id: "rec3",
    name: "Solitaire Diamond Ring",
    slug: "solitaire-diamond-ring",
    description: "A single brilliant-cut diamond set in a sleek 18K white gold band. The minimal bezel setting allows the stone to command full attention — a timeless symbol of commitment and refined taste.",
    price: 45000,
    originalPrice: 52000,
    images: [
      "/images/product-3.jpg",
    ],
    category: "Rings",
    subcategory: "Solitaire",
    tags: ["diamond", "white-gold", "engagement", "statement"],
    inStock: true,
    stockCount: 5,
    material: "18K White Gold, VS1 Diamond",
    weight: "2.8g",
    dimensions: "Stone: 0.5ct",
    featured: true,
    newArrival: false,
    bestseller: true,
    createdAt: "2024-01-10T10:00:00Z",
  },
  {
    id: "rec4",
    name: "Heritage Kundan Bangle Set",
    slug: "heritage-kundan-bangle-set",
    description: "A set of four hand-enamelled bangles featuring traditional Kundan work with uncut diamonds set in 22K gold. The vibrant Meenakari enamel work on the inner surface adds a hidden burst of colour.",
    price: 67500,
    images: [
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=800&q=80",
      "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=800&q=80",
    ],
    category: "Bangles",
    subcategory: "Kundan",
    tags: ["kundan", "diamond", "traditional", "wedding"],
    inStock: true,
    stockCount: 3,
    material: "22K Gold, Uncut Diamonds, Enamel",
    weight: "45g (set of 4)",
    dimensions: "Size: 2.6",
    featured: false,
    newArrival: false,
    bestseller: true,
    createdAt: "2024-01-05T10:00:00Z",
  },
  {
    id: "rec5",
    name: "Minimalist Bar Bracelet",
    slug: "minimalist-bar-bracelet",
    description: "A sleek horizontal gold bar on a fine chain bracelet. The clean geometry and polished finish make this an everyday essential that transitions seamlessly from boardroom to dinner.",
    price: 12500,
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&q=80",
      "https://images.unsplash.com/photo-1599643478518-17488fbbcd75?w=800&q=80",
    ],
    category: "Bracelets",
    subcategory: "Chains",
    tags: ["gold", "minimal", "daily-wear", "modern"],
    inStock: true,
    stockCount: 15,
    material: "18K Gold",
    weight: "2.1g",
    dimensions: "Length: 7 inches, Bar: 2cm",
    featured: false,
    newArrival: true,
    bestseller: false,
    createdAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "rec6",
    name: "Emerald Lotus Pendant",
    slug: "emerald-lotus-pendant",
    description: "A lotus-inspired pendant featuring a Colombian emerald at its centre, surrounded by pavé diamonds in 18K gold. The lotus symbolises purity and spiritual awakening in Indian tradition.",
    price: 38500,
    originalPrice: 42000,
    images: [
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=80",
    ],
    category: "Necklaces",
    subcategory: "Pendants",
    tags: ["emerald", "diamond", "gold", "spiritual"],
    inStock: true,
    stockCount: 6,
    material: "18K Gold, Colombian Emerald, Diamonds",
    weight: "5.4g",
    dimensions: "Pendant: 2cm x 2cm",
    featured: false,
    newArrival: true,
    bestseller: false,
    createdAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "rec7",
    name: "Rose Gold Hoop Earrings",
    slug: "rose-gold-hoop-earrings",
    description: "Classic hoop earrings in warm 18K rose gold with a satin-brushed finish. The medium size makes them versatile enough for both casual and formal occasions.",
    price: 22000,
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=800&q=80",
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80",
    ],
    category: "Earrings",
    subcategory: "Hoops",
    tags: ["rose-gold", "hoops", "daily-wear", "classic"],
    inStock: true,
    stockCount: 10,
    material: "18K Rose Gold",
    weight: "3.8g",
    dimensions: "Diameter: 2.5cm",
    featured: false,
    newArrival: false,
    bestseller: true,
    createdAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "rec8",
    name: "Temple Jewellery Choker",
    slug: "temple-jewellery-choker",
    description: "An ornate choker necklace inspired by South Indian temple architecture, featuring intricate filigree work in 22K gold with ruby and pearl accents. A statement piece for weddings and festive occasions.",
    price: 95000,
    images: [
      "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=800&q=80",
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=800&q=80",
    ],
    category: "Necklaces",
    subcategory: "Chokers",
    tags: ["temple", "gold", "ruby", "pearl", "wedding"],
    inStock: true,
    stockCount: 2,
    material: "22K Gold, Rubies, Pearls",
    weight: "68g",
    dimensions: "Length: 14 inches",
    featured: false,
    newArrival: false,
    bestseller: false,
    createdAt: "2024-01-08T10:00:00Z",
  },
  {
    id: "rec9",
    name: "Sapphire Stud Earrings",
    slug: "sapphire-stud-earrings",
    description: "Round-cut Ceylon blue sapphires set in 18K white gold with a diamond halo. The deep blue hue is reminiscent of the Indian monsoon sky — rich, mysterious, and captivating.",
    price: 32000,
    originalPrice: 36000,
    images: [
      "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800&q=80",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=80",
    ],
    category: "Earrings",
    subcategory: "Studs",
    tags: ["sapphire", "white-gold", "diamond", "elegant"],
    inStock: true,
    stockCount: 7,
    material: "18K White Gold, Ceylon Sapphire, Diamonds",
    weight: "2.4g",
    dimensions: "Stone: 0.8ct each",
    featured: false,
    newArrival: true,
    bestseller: false,
    createdAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "rec10",
    name: "Antique Gold Jhumka",
    slug: "antique-gold-jhumka",
    description: "Traditional bell-shaped jhumka earrings with an antique gold finish, featuring intricate temple motifs and pearl drops. The oxidised detailing adds vintage character to this heritage design.",
    price: 28000,
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=800&q=80",
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80",
    ],
    category: "Earrings",
    subcategory: "Jhumkas",
    tags: ["antique", "gold", "pearl", "traditional", "wedding"],
    inStock: true,
    stockCount: 4,
    material: "22K Gold, Pearls",
    weight: "8.5g (pair)",
    dimensions: "Length: 4cm",
    featured: false,
    newArrival: false,
    bestseller: true,
    createdAt: "2024-01-12T10:00:00Z",
  },
  {
    id: "rec11",
    name: "Diamond Tennis Bracelet",
    slug: "diamond-tennis-bracelet",
    description: "A continuous line of brilliant-cut diamonds set in 18K white gold. The classic tennis bracelet design offers timeless elegance and catches light from every angle.",
    price: 125000,
    images: [
      "/images/product-4.jpg",
    ],
    category: "Bracelets",
    subcategory: "Tennis",
    tags: ["diamond", "white-gold", "luxury", "statement"],
    inStock: true,
    stockCount: 2,
    material: "18K White Gold, Diamonds",
    weight: "12g",
    dimensions: "Length: 7 inches, 3ct total diamond weight",
    featured: true,
    newArrival: false,
    bestseller: false,
    createdAt: "2024-01-25T10:00:00Z",
  },
  {
    id: "rec12",
    name: "Mangalsutra Modern",
    slug: "mangalsutra-modern",
    description: "A contemporary reinterpretation of the traditional mangalsutra, featuring a single black bead strand with a minimal gold pendant. Designed for the modern woman who honours tradition with subtlety.",
    price: 15500,
    images: [
      "https://images.unsplash.com/photo-1599643478518-17488fbbcd75?w=800&q=80",
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&q=80",
    ],
    category: "Necklaces",
    subcategory: "Mangalsutra",
    tags: ["gold", "traditional", "modern", "daily-wear"],
    inStock: true,
    stockCount: 9,
    material: "22K Gold, Black Beads",
    weight: "3.5g",
    dimensions: "Length: 20 inches",
    featured: false,
    newArrival: true,
    bestseller: false,
    createdAt: "2024-03-20T10:00:00Z",
  },
]

export const mockCategories = [
  "All",
  "Necklaces",
  "Earrings",
  "Rings",
  "Bracelets",
  "Bangles",
]

export const mockFAQ: FAQItem[] = [
  {
    question: "What is your return and exchange policy?",
    answer: "We offer a 7-day return policy for unworn items in original packaging with the certificate of authenticity. Custom-made and engraved pieces cannot be returned. Exchanges are accepted within 14 days for size adjustments on rings and bangles.",
    category: "Orders & Shipping",
  },
  {
    question: "How do I know the gold purity is genuine?",
    answer: "Every piece comes with a BIS Hallmark certificate verifying the gold purity (22K or 18K as stated). We also provide a certificate of authenticity for diamonds and gemstones from certified laboratories. All items are tested for purity before dispatch.",
    category: "Product & Quality",
  },
  {
    question: "Do you offer custom jewellery design?",
    answer: "Yes, we offer bespoke design services. Share your vision with us via WhatsApp or visit our studio in Jaipur. Custom pieces require a 50% advance and typically take 3-4 weeks for completion. We provide design sketches for approval before crafting begins.",
    category: "Custom Orders",
  },
  {
    question: "How does the WhatsApp checkout work?",
    answer: "After adding items to your bag, click 'Checkout via WhatsApp'. We generate a pre-filled order summary message that opens in your WhatsApp with our store number. Our team will confirm availability, share payment details (UPI/Bank Transfer), and process your order once payment is received.",
    category: "Orders & Shipping",
  },
  {
    question: "What payment methods do you accept?",
    answer: "We accept UPI (Google Pay, PhonePe, Paytm), bank transfer, and cash on delivery for select locations. All online payments are processed through secure channels. We do not store any payment information.",
    category: "Orders & Shipping",
  },
  {
    question: "How long does shipping take?",
    answer: "Domestic orders within India are delivered within 3-5 business days via insured courier. International shipping takes 7-14 business days. Each order is fully insured and requires signature upon delivery. Tracking details are shared via WhatsApp.",
    category: "Orders & Shipping",
  },
  {
    question: "Can I resize a ring after purchase?",
    answer: "Yes, we offer one complimentary resizing within 30 days of purchase. Additional resizings are charged at ₹500. Please note that some designs with continuous patterns cannot be resized. Contact us via WhatsApp to arrange resizing.",
    category: "Product & Quality",
  },
  {
    question: "How should I care for my jewellery?",
    answer: "Store pieces separately in the provided pouch to prevent scratches. Avoid contact with perfumes, lotions, and household chemicals. Clean gold jewellery with mild soap and warm water using a soft brush. For diamond and gemstone pieces, professional cleaning every 6 months is recommended.",
    category: "Product & Quality",
  },
  {
    question: "Do you provide gift packaging?",
    answer: "Every order comes in our signature Chinkara Jewels box with a silk pouch and authenticity card. Premium gift wrapping with a handwritten note is available at no extra charge — just mention it during checkout.",
    category: "Orders & Shipping",
  },
  {
    question: "Is my personal information secure?",
    answer: "Absolutely. We use industry-standard encryption for all data. Your phone number and address are only used for order fulfilment and shipping updates. We never share customer data with third parties. You can request data deletion at any time.",
    category: "Account & Privacy",
  },
  {
    question: "How do I track my order?",
    answer: "Once dispatched, you will receive a tracking link via WhatsApp and email. You can also log into your account dashboard to view real-time order status. Our team is available on WhatsApp for any shipping queries.",
    category: "Orders & Shipping",
  },
  {
    question: "Do you offer EMI or instalment payments?",
    answer: "We currently do not offer EMI directly. However, you can use credit card EMI options through your bank for orders above ₹20,000. Contact us for details on available payment plans.",
    category: "Orders & Shipping",
  },
]

export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    userId: "user1",
    items: [
      { product: mockProducts[0], quantity: 1 },
      { product: mockProducts[2], quantity: 1 },
    ],
    total: 73500,
    status: "delivered",
    createdAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "ORD-002",
    userId: "user1",
    items: [
      { product: mockProducts[1], quantity: 2 },
    ],
    total: 37000,
    status: "shipped",
    createdAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "ORD-003",
    userId: "user2",
    items: [
      { product: mockProducts[3], quantity: 1 },
      { product: mockProducts[6], quantity: 1 },
    ],
    total: 89500,
    status: "confirmed",
    createdAt: "2024-03-20T10:00:00Z",
  },
  {
    id: "ORD-004",
    userId: "user3",
    items: [
      { product: mockProducts[10], quantity: 1 },
    ],
    total: 125000,
    status: "pending",
    createdAt: "2024-03-22T10:00:00Z",
  },
  {
    id: "ORD-005",
    userId: "user1",
    items: [
      { product: mockProducts[4], quantity: 1 },
      { product: mockProducts[5], quantity: 1 },
    ],
    total: 51000,
    status: "delivered",
    createdAt: "2024-02-10T10:00:00Z",
  },
]

export const mockUsers: User[] = [
  {
    id: "user1",
    email: "priya.sharma@email.com",
    name: "Priya Sharma",
    photoURL: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
    wishlist: ["rec2", "rec5", "rec9"],
    orders: ["ORD-001", "ORD-002", "ORD-005"],
    createdAt: "2024-01-01T10:00:00Z",
  },
  {
    id: "user2",
    email: "arjun.patel@email.com",
    name: "Arjun Patel",
    photoURL: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
    wishlist: ["rec3", "rec7"],
    orders: ["ORD-003"],
    createdAt: "2024-02-15T10:00:00Z",
  },
  {
    id: "user3",
    email: "meera.reddy@email.com",
    name: "Meera Reddy",
    photoURL: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
    wishlist: ["rec10", "rec11"],
    orders: ["ORD-004"],
    createdAt: "2024-03-01T10:00:00Z",
  },
]
